# Trapezoidal Numerical Method for Integration

In [1]:
def f(x):
    return(1/(1+x))
a=0;b=1;n=6;h=(b-a)/n
import numpy as np
x=np.arange(a,b+0.1,h)
y=f(x)
s=y[0]+y[n]
s1=(h/2)*(s+2*sum(y[np.arange(1,n)]));s1


0.6948773448773449

# Simphsons 1/3 rd Numerical Method for Integration


In [2]:
def f(x):
    return(1/(1+x))
a=0;b=1;n=6;h=(b-a)/n
import numpy as np
x=np.arange(a,b+0.1,h)
y=f(x)
s=y[0]+y[n]
s=(h/3)*(s+4*sum(y[np.arange(1,n,2)])+2*sum(y[np.arange(2,n,2)]));s

0.6931697931697932

# Simphsons 3/8 th Numerical Method for Integration


In [1]:
def f(x):
    return(1/(1+x))
a=0;b=1;n=6;h=(b-a)/n
import numpy as np
x=np.arange(a,b+0.1,h)
y=f(x)
s=y[0]+y[n]
a=np.arange(3,n,3) #Multiple of 3
b=np.arange(1,n)
l=[]
for i in b:
    if(i not in a ):
        l.append(i)
l 
l=np.array(l) #Non Multiple of 3
s=(3*h/8)*(s+2*sum(y[np.arange(3,n,3)])+3*sum(y[l]));s


0.6931953463203464

In [21]:
def f(x):
    return(1/(1+x))
a=0;b=1;n=6;h=(b-a)/n
import numpy as np
x=np.arange(a,b+0.1,h)
y=f(x)
3*h/8*(y[0]+y[n]+3*sum(y[1:n])-sum(y[np.arange(3,n,3)]))

0.6931953463203463

In [17]:
y

array([1.        , 0.85714286, 0.75      , 0.66666667, 0.6       ,
       0.54545455, 0.5       ])

In [18]:
y[1:2]

array([0.85714286])

# Trial and Errors

In [6]:
b=np.arange(1,n+1,1);b
b.pop([0,n+1,a])


AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [7]:
np.arange(3,n,3)

array([3])

In [8]:
sum(y[np.arange(2,n+1,2)])

1.85

In [9]:
sum(y[np.arange(1,n,2)])

2.069264069264069

In [10]:
y[n]

0.5

In [11]:
b=np.arange(1,n+1)
b1=np.array([1,2,5])

In [1]:
l=[]
for i in b:
    if(i not in b1 ):
        l.append(i)
l        

NameError: name 'b' is not defined